Lint/Debugger:
  Exclude:
    - bin/console

# Missing top level class documentation comment.
Style/Documentation:
  Enabled: false

# Avoid the use of double negation (!!)
Style/DoubleNegation:
  Enabled: false
